name: Build and Publish Docker Image

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Pi-hole Docker version
        id: pihole-version
        run: |
          PIHOLE_VERSION=$(curl -sL https://registry.hub.docker.com/v2/repositories/pihole/pihole/tags?page_size=100 | \
          jq -r '.results[].name' | grep '^20' | sort -rV | head -n1)
          if [ -z "$PIHOLE_VERSION" ]; then
            echo "Failed to fetch Pi-hole version"
            exit 1
          fi
          echo "version=${PIHOLE_VERSION}" >> $GITHUB_OUTPUT
          echo "Found Pi-hole version: ${PIHOLE_VERSION}"

      - name: Check if new version
        id: check-version
        run: |
          if [ -z "${{ steps.pihole-version.outputs.version }}" ]; then
            echo "Invalid Pi-hole version"
            exit 1
          fi
          
          CURRENT_VERSION=$(curl -sL https://hub.docker.com/v2/repositories/bariscimen/pihole-dns-over-https/tags | \
            jq -r '.results[].name' | grep '^20' | sort -rV | head -n1)
          
          if [ -z "$CURRENT_VERSION" ]; then
            echo "First build - proceeding"
            echo "should_build=true" >> $GITHUB_OUTPUT
          elif [ "${{ steps.pihole-version.outputs.version }}" == "$CURRENT_VERSION" ]; then
            echo "No new version found. Exiting."
            exit 0
          else
            echo "New version found: ${{ steps.pihole-version.outputs.version }}"
            echo "should_build=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        if: steps.check-version.outputs.should_build == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: steps.check-version.outputs.should_build == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: steps.check-version.outputs.should_build == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: steps.check-version.outputs.should_build == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/386,linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          build-args: |
            PIHOLE_VERSION=${{ steps.pihole-version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            bariscimen/pihole-dns-over-https:latest
            bariscimen/pihole-dns-over-https:${{ steps.pihole-version.outputs.version }}