name: Build and Publish Docker Image

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get Pi-hole Docker version
        id: pihole-version
        run: |
          PIHOLE_VERSION=$(curl -s https://registry.hub.docker.com/v2/repositories/pihole/pihole/tags?page_size=100 | \
          jq -r '.results[].name' | grep '^20' | sort -rV | head -n1)
          if [ -z "$PIHOLE_VERSION" ]; then
            echo "Failed to fetch Pi-hole version"
            exit 1
          fi
          echo "version=${PIHOLE_VERSION}" >> $GITHUB_OUTPUT
          echo "Found Pi-hole version: ${PIHOLE_VERSION}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/arm64/v8
          push: true
          tags: |
            bariscimen/pihole-dns-over-https:latest
            bariscimen/pihole-dns-over-https:${{ steps.pihole-version.outputs.version }}